### ISSUE TITLE
Should I/O be Serialized, or should we accept text/base64/etc.. and parse?

### ISSUE THREAD

**Issue by Sean-Der** [webrtc-for-the-curious/explainer#3]
It might be nice to have an API that accepts anything and does heuristics. If that fails it will return an error.

That could be frustrating for users that already have a SessionDescription/JSON though? We could provide two APIs (one for JSON/one for text?)

**Comment by davidzhao** [comment]
Having a single magical interface would be great :) Most folks are likely copying/pasting an SDP from somewhere else, rather than using the tool programmatically

**Comment by Sean-Der** [comment]
:+1: These are the inputs I see.

* SDP
* SessionDescriptionInit (JSON that has Type+SDP field)

These values may be base64 encoded.

**Comment by davidzhao** [comment]
that makes sense. would be great to be able to autodetect it. Especially for new users of WebRTC, the difference might not be very clear. We could perform these steps:
1. checking if base64 encoded
2. checking if JSON
3. extracting SDP
4. indicating to user which type we've identified
